[colors]
bg           = #0d0d0d
label        = #cdd6f4
hint         = #6c7086
gear_normal  = #585b70
gear_hover   = #cdd6f4
circle_hover = #1e1e2e
circle_click = #313244
popover_bg   = #1e1e2e
popover_field = #313244
popover_fg   = #cdd6f4

# lock-screen specific keys
clock_fg     = #cdd6f4
date_fg      = #6c7086
user_fg      = #45475a
error_fg     = #f38ba8
entry_bg     = #1e1e2e
entry_fg     = #cdd6f4
entry_hl     = #585b70
