[colors]
bg           = #181818
label        = #dedede
hint         = #777777
gear_normal  = #777777
gear_hover   = #dedede
circle_hover = #252525
circle_click = #3b3b3b
popover_bg   = #252525
popover_field = #3b3b3b
popover_fg   = #b9b9b9
