[colors]
bg           = #333c43
label        = #d3c6aa
hint         = #859289
gear_normal  = #859289
gear_hover   = #d3c6aa
circle_hover = #3a464c
circle_click = #434f55
popover_bg   = #293136
popover_field = #3a464c
popover_fg   = #9da9a0
