[colors]
bg           = #272e33
label        = #d3c6aa
hint         = #859289
gear_normal  = #859289
gear_hover   = #d3c6aa
circle_hover = #2e383c
circle_click = #374145
popover_bg   = #1e2326
popover_field = #2e383c
popover_fg   = #9da9a0
