[colors]
bg           = #181818
label        = #e4e4ef
hint         = #9e95c7
gear_normal  = #9e95c7
gear_hover   = #e4e4ef
circle_hover = #282828
circle_click = #353535
popover_bg   = #1c1c1c
popover_field = #282828
popover_fg   = #c9c9d9
