[colors]
bg           = #282828
label        = #ebdbb2
hint         = #665c54
gear_normal  = #665c54
gear_hover   = #ebdbb2
circle_hover = #32302f
circle_click = #504945
popover_bg   = #1d2021
popover_field = #32302f
popover_fg   = #a89984
