[colors]
bg           = #282828
label        = #d4be98
hint         = #7c6f64
gear_normal  = #7c6f64
gear_hover   = #d4be98
circle_hover = #32302f
circle_click = #45403d
popover_bg   = #32302f
popover_field = #45403d
popover_fg   = #a89984
