[colors]
bg           = #282828
label        = #ebdbb2
hint         = #928374
gear_normal  = #928374
gear_hover   = #ebdbb2
circle_hover = #3c3836
circle_click = #504945
popover_bg   = #1d2021
popover_field = #3c3836
popover_fg   = #a89984
