[colors]
bg           = #181616
label        = #c5c9c5
hint         = #625e5a
gear_normal  = #625e5a
gear_hover   = #c5c9c5
circle_hover = #282727
circle_click = #393836
popover_bg   = #0d0c0c
popover_field = #282727
popover_fg   = #a6a69c
