[colors]
bg           = #2c2525
label        = #fff1f3
hint         = #948a8b
gear_normal  = #948a8b
gear_hover   = #fff1f3
circle_hover = #403838
circle_click = #5b5353
popover_bg   = #211c1c
popover_field = #403838
popover_fg   = #c3b7b8
