[colors]
bg           = #2d2a2e
label        = #fcfcfa
hint         = #939293
gear_normal  = #939293
gear_hover   = #fcfcfa
circle_hover = #403e41
circle_click = #5b595c
popover_bg   = #221f22
popover_field = #403e41
popover_fg   = #c1c0c0
