[colors]
bg           = #222222
label        = #f7f1ff
hint         = #8b888f
gear_normal  = #8b888f
gear_hover   = #f7f1ff
circle_hover = #363537
circle_click = #525053
popover_bg   = #191919
popover_field = #363537
popover_fg   = #bab6c0
