[colors]
bg           = #272822
label        = #fdfff1
hint         = #919288
gear_normal  = #919288
gear_hover   = #fdfff1
circle_hover = #3b3c35
circle_click = #57584f
popover_bg   = #1d1e19
popover_field = #3b3c35
popover_fg   = #c0c1b5
