[colors]
bg           = #282a3a
label        = #eaf2f1
hint         = #888d94
gear_normal  = #888d94
gear_hover   = #eaf2f1
circle_hover = #3a3d4b
circle_click = #535763
popover_bg   = #1e1f2b
popover_field = #3a3d4b
popover_fg   = #b2b9bd
