[colors]
bg           = #011627
label        = #acb4c2
hint         = #4b6479
gear_normal  = #4b6479
gear_hover   = #acb4c2
circle_hover = #092236
circle_click = #153a53
popover_bg   = #092236
popover_field = #0e293f
popover_fg   = #7c8fa5
