[colors]
bg           = #192330
label        = #cdcecf
hint         = #738091
gear_normal  = #738091
gear_hover   = #cdcecf
circle_hover = #212e3f
circle_click = #2b3b51
popover_bg   = #212e3f
popover_field = #2b3b51
popover_fg   = #aeafb0
