[colors]
bg           = #1b1e28
label        = #e4f0fb
hint         = #767c9d
gear_normal  = #767c9d
gear_hover   = #a6accd
circle_hover = #252635
circle_click = #303340
popover_bg   = #171922
popover_field = #252635
popover_fg   = #a6accd
