[colors]
bg           = #191724
label        = #e0def4
hint         = #6e6a86
gear_normal  = #6e6a86
gear_hover   = #e0def4
circle_hover = #21202e
circle_click = #403d52
popover_bg   = #1f1d2e
popover_field = #26233a
popover_fg   = #908caa
