[colors]
bg           = #262335
label        = #ffffff
hint         = #848bbd
gear_normal  = #848bbd
gear_hover   = #ffffff
circle_hover = #2a2139
circle_click = #403d4e
popover_bg   = #241b2f
popover_field = #403d4e
popover_fg   = #c8ccd4
