[colors]
bg           = #10141e
label        = #f8fafc
hint         = #90a1b9
gear_normal  = #90a1b9
gear_hover   = #74d4ff
circle_hover = #293b4a
circle_click = #364153
popover_bg   = #030712
popover_field = #202653
popover_fg   = #f8fafc
