[colors]
bg           = #222436
label        = #c8d3f5
hint         = #636da6
gear_normal  = #636da6
gear_hover   = #c8d3f5
circle_hover = #2f334d
circle_click = #3b4261
popover_bg   = #1e2030
popover_field = #2f334d
popover_fg   = #828bb8
