[colors]
bg           = #3f3f3f
label        = #dcdccc
hint         = #7f9f7f
gear_normal  = #7f9f7f
gear_hover   = #dcdccc
circle_hover = #494949
circle_click = #5f5f5f
popover_bg   = #3b3b3b
popover_field = #494949
popover_fg   = #c0c0a0
