[colors]
bg           = #191919
label        = #c2c2c2
hint         = #727272
gear_normal  = #727272
gear_hover   = #c2c2c2
circle_hover = #252525
circle_click = #303030
popover_bg   = #141414
popover_field = #252525
popover_fg   = #aaaaaa
